registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views
from registro.views import *
from django.conf import settings
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    #url(r'^$', Index.as_view(), name='index'),
    url(r'^$', buscar, name='buscar'),
    url(r'^lista_certificados$', login_required(views.Lista_Certificados.as_view()), name='lista_certificados'),
    url(r'^subir_data$', login_required(views.Subir_data.as_view()), name='subir_data'),
    url(r'^subir_data_csv$', login_required(views.Subir_data_csv.as_view()), name='subir_data_csv'),
    url(r'^guardar_certificado$', login_required(views.Guardar_Certificado.as_view()), name='guardar_certificado'),
    url(r'^editar_certificado/(?P<pk>\d+)$', login_required(views.Editar_Certificado.as_view()), name='editar_certificado'),
    url(r'^borrar_certificado/(?P<pk>\d+)$', login_required(views.Borrar_Certificado.as_view()), name='borrar_certificado'),
    # Definiendo la url que va a servir los certificados para que puedan ser descargados.
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    # Definiendo la url que va a servir los certificados para que puedan ser descargados luego de filtrar.
    url(r'^busqueda/media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^descomprimir_zip$', login_required(descomprimir_zip), name='descomprimir_zip'),
    #url(r'^insertar_csv$', login_required(insertar_csv), name='insertar_csv'),
    url(r'^insertar_data_csv$', views.insertar_data_csv, name='insertar_data_csv'),
    url(r'^busqueda/$', busqueda, name='busqueda'),
    url(r'^salir$', login_required(views.Salir.as_view()), name='salir'),
)

repositorio_certificados/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('registro.urls', namespace='registro')),
]

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse


class Data(models.Model):
    """
    Modelo de la data que se sube al servidor.
    """
    descripcion = models.CharField(max_length=255, blank=True, null=True)
    data_zip = models.FileField(upload_to='', blank=True, null=True)

    def __unicode__(self):
        return self.descripcion


class Certificado(models.Model):
    """
    Modelo del certificado digital que se sube al servidor.
    """
    nombre_completo = models.CharField(max_length=255, blank=True, null=True)
    cedula = models.CharField(max_length=255, blank=True, null=True)
    evento_curso = models.CharField(max_length=255, blank=True, null=True)
    rol = models.CharField(max_length=255, blank=True, null=True)
    certificado = models.FileField(upload_to='', blank=True, null=True)
    uploaded_at = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('registro:editar_certificado', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.cedula

registro/forms.py
# -*- coding: utf-8 -*-
from django import forms
from registro.models import Certificado, Data


class DataForm(forms.ModelForm):
    """
    Formulario de la data que se sube al servidor.
    """
    class Meta:
        model = Data
        fields = ('descripcion','data_zip')


class CertificadoForm(forms.ModelForm):
    """
    Formulario del certificado digital que se sube al servidor.
    """
    class Meta:
        model = Certificado
        fields = ('nombre_completo','cedula','evento_curso','rol','certificado','uploaded_at')

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView,ListView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from registro.models import Certificado, Data
from registro.forms import CertificadoForm, DataForm
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import render_to_response
from django.template import RequestContext
from datetime import datetime
import os
import csv


class Subir_data(SuccessMessageMixin, CreateView):
    """
    Clase que permite subir la data .zip en el servidor.
    """
    model = Data
    form_class = DataForm
    template_name = "registro/subir_data.html"
    success_url = reverse_lazy('registro:subir_data')
    success_message = "La data se guardo con éxito"

    def post(self, request, *args, **kwargs):
        self.object = None
        #print "----------------"
        #print "Entro en el método post de Subir_data"
        #print "----------------"
        #a = os.getcwd()
        #print a
        #os.chdir(a+'/media/')
        #os.system("ls -l")
        #print "Listo el contenido del directorio"
        return super(Subir_data, self).post(request, *args, **kwargs)


class Subir_data_csv(SuccessMessageMixin, CreateView):
    """
    Clase que permite subir la data .csv en el servidor.
    """
    model = Data
    form_class = DataForm
    template_name = "registro/subir_data_csv.html"
    success_url = reverse_lazy('registro:subir_data')
    success_message = "La data se guardo con éxito"

    def post(self, request, *args, **kwargs):
        self.object = None
        return super(Subir_data_csv, self).post(request, *args, **kwargs)


def descomprimir_zip(request):
    """
    Función que sirve para descomprimir y luego borrar el .zip adjuntado
    anteriormente.
    """
    a = os.getcwd() # Guardar el directorio actual en la variable a.
    #os.chdir(a+'/media') # Cambiarse a /media desde la raíz del proyecto.
    os.chdir(settings.MEDIA_ROOT) # Cambiarse a /media desde la raíz del proyecto.
    os.system("unzip *.zip") # Descomprimir todos los .zip del directorio.
    os.system("rm *.zip") # Remover todos los .zip del directorio.
    os.chdir(a) # Cambiarse al directorio raíz del proyecto.
    messages = ['¡Se descomprimió el .zip con éxito y luego se borró el .zip!']
    return render_to_response('registro/buscar.html', {'messages': messages}, context_instance=RequestContext(request))


def insertar_csv(request):
    """
    Función que permite insertar la data .csv en la base de datos sqlite.
    """
    a = os.getcwd() # Guardar el directorio actual en la variable a.
    #os.system("bash insert_csv.sh") # Ejecutar el script en bash.
    os.system("bash insert_csv.sh %s %s" % (settings.MEDIA_ROOT, settings.DATABASES['default']['NAME'])) # Ejecutar el script en bash.
    os.chdir(a) # Cambiarse al directorio raíz del proyecto.
    messages = ['¡Se insertó la data .csv correctamente!']
    return render_to_response('registro/buscar.html', {'messages': messages}, context_instance=RequestContext(request))


def insertar_data_csv(request, template_name='registro/lista_certificados.html'):
    """
    Función que permite insertar los datos del fichero CSV en la base de datos.
    """
    with open(settings.MEDIA_ROOT+'/data_final.csv', 'r') as listado:
        datos = csv.reader(listado, delimiter=',') # Separar la data por coma.
        for row in datos:
            nombre_completo = row[0]
            cedula = row[1]
            evento_curso = row[2]
            rol = row[3]
            certificado = row[4]
            uploaded_at = row[5]
            Certificado.objects.create(nombre_completo=nombre_completo, cedula=cedula, evento_curso=evento_curso, rol=rol, certificado=certificado,uploaded_at=uploaded_at)
    listado.close()
    a = os.getcwd() # Guardar el directorio actual en la variable a.
    os.system("bash delete_csv.sh %s %s" % (settings.MEDIA_ROOT, settings.DATABASES['default']['NAME'])) # Ejecutar el script en bash.
    os.chdir(a) # Cambiarse al directorio raíz del proyecto.
    messages = ['¡Se insertó la data .csv correctamente!']
    return render_to_response('registro/buscar.html', {'messages': messages}, context_instance=RequestContext(request))

def formato_fecha(request):
    """
    Función que cambia el formato de hora y fecha de python
    """
    uploaded_at = datetime.now()
    fecha_hora = uploaded_at.strftime("%d-%m-%Y %H:%M")
    return render('registro/lista_certificados.html', {'uploaded_at': fecha_hora})


class Guardar_Certificado(SuccessMessageMixin, CreateView):
    """
    Clase que permite guardar los certificados, se guardar en /media.
    """
    model = Certificado
    form_class = CertificadoForm
    template_name = "registro/guardar_certificado.html"
    success_url = reverse_lazy('registro:buscar')
    success_message = "Se guardó el certificado con éxito"


class Lista_Certificados(ListView):
    """
    Clase que permite listar los certificados registrados.
    """
    model = Certificado
    #queryset = Certificado.objects.order_by('-uploaded_at')
    template_name = "registro/lista_certificados.html"


class Editar_Certificado(SuccessMessageMixin, UpdateView):
    """
    Clase que permite editar los certificados registrados.
    """
    template_name = "registro/editar_certificado.html"
    form_class = CertificadoForm
    model = Certificado
    success_message = "Se actualizó la información con éxito"
    success_url = reverse_lazy('registro:lista_certificados')


class Borrar_Certificado(SuccessMessageMixin, DeleteView):
    """
    Clase que permite borrar los certificados.
    """
    form_class = CertificadoForm
    model = Certificado
    success_message = "Se eliminó la información con éxito"
    success_url = reverse_lazy('registro:lista_certificados')


def buscar(request):
    """
    Función que muestra la plantilla con el formulario de búsqueda.
    """
    return render(request, 'registro/buscar.html')


def busqueda(request):
    """
    Función que permite hacer el query con los certificados ya filtrados.
    """
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        #certificados = Certificado.objects.filter(cedula__icontains=q)
        certificados = Certificado.objects.filter(cedula=q).order_by('-uploaded_at')
        if certificados:
            #certificados = Certificado.objects.order_by('-uploaded_at')
            return render(request, 'registro/buscar.html',  {'certificados': certificados, 'query': q})
        else:
            messages = ['No se encontró ningún certificado.']
            return render_to_response('registro/buscar.html', {'messages': messages})
    else:
        messages = ['Por favor introduce una cédula de identidad.']
        return render_to_response('registro/buscar.html', {'messages': messages})

class Salir(View):
    """
    Clase que permite cerrar la sesión de usuario.
    """

    def get(self, request):
        """
        Método que redireccíona cuando se cierra la sesión.
        """
        logout(request)
        return redirect('/')

registro/templates/registro/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}
    <link rel="icon" href="{% static 'img/favicon-2021.png' %}">
    <title>
      {% block titulo %}Repositorio de certificados digitales de CENDITEL{% endblock %}
    </title>
    {% load staticfiles %}
    <!-- Bootstrap Styles - css
    ================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Styles - css
    ================================================== -->
    <link href="{% static 'css/theme.css' %}?version=1.1" rel="stylesheet">
    <!-- Others - js
    ================================================== -->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- Jquery - js
    ================================================== -->
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <!-- Bootstrap - js
    ================================================== -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bug fix - js
    ================================================== -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </head>
  <body>

    <!-- navbar cintillo
    ================================================== -->
    <nav class="navbar navbar-default navbar-fixed-top navbar-cintillo">
    <div class="container">
      <div align="center">
        <img class="cintillo_up" src="{% static 'img/cintillo_2021.png' %}" width="100%"></img>
      </div>
    </div>
    </nav>
    <!-- navbar cintillo end -->

    <br />
    <br />
    <br />

    <!-- Navbar
    ================================================== -->
    <nav class="navbar navbar-default navbar-default-menu">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="https://www.cenditel.gob.ve/certificados">
            <i class="glyphicon glyphicon-home"></i>
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          {% if request.user.is_authenticated %}
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="glyphicon glyphicon-menu-hamburger"></i>
                &nbsp;Menú <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'registro:subir_data' %}">
                    <i class="glyphicon glyphicon-ok"></i>
                    Subir data .zip
                  </a>
                </li>
                <li>
                  <a href="{% url 'registro:descomprimir_zip' %}">
                    <i class="glyphicon glyphicon-ok"></i>
                    Descomprimir .zip y borrar .zip
                  </a>
                </li>
                <li>
                  <a href="{% url 'registro:subir_data_csv' %}">
                    <i class="glyphicon glyphicon-ok"></i>
                    Subir data .csv
                  </a>
                </li>
                <li>
                  <a href="{% url 'registro:insertar_data_csv' %}">
                    <i class="glyphicon glyphicon-ok"></i>
                    Insertar data .csv
                  </a>
                </li>
                <li>
                  <a href="{% url 'registro:guardar_certificado' %}">
                    <i class="glyphicon glyphicon-ok"></i>
                    Subir certificado
                  </a>
                </li>
                <li>
                  <a href="{% url 'registro:lista_certificados' %}">
                    <i class="glyphicon glyphicon-ok"></i>
                    Lista de certificados
                  </a>
                </li>
                <li>
                  <a href="{% url 'registro:salir' %}">
                    <i class="glyphicon glyphicon-log-out"></i>
                    Cerrar sesión
                  </a>
                </li>
              </ul>
            </li>
          </ul>
          {% else %}
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- End navbar -->

    <!-- section-white
    ================================================== -->
    <div class="jumbotron section-white">

      <!-- Container
      ================================================== -->
      <div class="container theme-showcase" role="main">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-success alert-dismissable">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>
                  {% if message.tags %}{% endif %}
                  {{ message }}
                </strong>
            </div>
          {% endfor %}
        {% endif %}
        <!--br /-->
        {% block cuerpo %}
        {% endblock %}
        <div align="center">
          <hr />
          <h5>Nuestros certificados están firmados electrónicamente, luego<br />
          de descargarlos puede verificar la Firma electrónica usando nuestro<br />
          Portal de Firma Electrónica y Verificación.</h5>
          <img src="{% static 'img/banner_murachi.png' %}" width="40%">
          <a href="https://murachi.cenditel.gob.ve" target="_blank">
            <button class="btn btn-default btn-grad-green">VERIFICAR</button>
          </a>
        </div>
      </div>
      <!-- End Container -->

    </div>
    <!-- End section-white -->

    <!-- section-blue
    ================================================== -->
    <div class="jumbotron section-blue">

      <div class="container">

        <div class="well-footer">
          <div align="center">
            <b>
              <a href="http://www.cenditel.gob.ve" target="_blank">
                Desarrollado en el Centro Nacional de Desarrollo e Investigacion en Tecnologias Libres - CENDITEL
              </a>
              <br />
              <br />
              <a href="http://derechoinformatico.cenditel.gob.ve/licencia-de-contenido/" target="_blank">
                <img src="{% static 'img/lc-lc.png' %}" width="100px"></img>
              </a>
              <a href="http://derechoinformatico.cenditel.gob.ve/licencia-de-software/" target="_blank">
                <img src="{% static 'img/lc-ls-icon.png' %}" width="100px"></img>
              </a>
            </b>
          </div>
        </div>

      </div>

    </div>
    <!-- End section-blue -->

</body>
<script src="{% static 'js/scripts.js' %}"></script>
</html>

registro/templates/registro/buscar.html
{% extends "registro/base.html" %}
{% block titulo %}Repositorio de certificados digitales de CENDITEL{% endblock %}
{% block cuerpo %}
<script type="text/javascript">
  document.oncontextmenu = function(){return false;}
</script>
<div align="center">
  <h1>Repositorio de Certificados Digitales</h1>
  <br />
  <form action="{% url 'registro:busqueda' %}" method="get" onsubmit="return checkform(this);">
    <h4>
      Por favor escriba su cédula de identidad o número de identificación y el código
      <input type="hidden" id="txtCaptcha"/>
      <span id="txtCaptchaDiv"></span>
    </h4>
    <br />
    <input type="text" name="q" id="txtInput2" placeholder="Cédula ó ID" maxlength="20" min="999999" required>
    <br />
    <br />
    <input type="text" name="txtInput1" id="txtInput1" placeholder="Código" required/>
    <br />
    <br />
    <input type="submit" class="btn btn-default btn-grad" value="BUSCAR">
  </form>
  <br />
  {% if certificados %}
  <p><h4>Estás buscando la cédula o número de identificación: <strong>{{ query }}</strong></h4></p>
    <span class="certificados_encontrados"><h4>Certificados encontrados: {{ certificados|length }} certificado/s.</h4></span>
    <br />
    <br />
    <table class="table table-striped">
      <thead>
        <tr>
          <th><b>Nombre y Apellido</b></th>
          <th><b>Cédula o ID</b></th>
          <th><b>Evento / Curso</b></th>
          <th><b>Rol</b></th>
          <th><b>Fecha</b></th>
          <th><b>Ubicación electrónica</b></th>
        </tr>
      </thead>
      {% for x in certificados %}
      <tbody>
        <tr>
          <td>
            {{ x.nombre_completo }}
          </td>
          <td>
            {{ x.cedula }}
          </td>
          <td>
            {{ x.evento_curso }}
          </td>
          <td>
            {{ x.rol }}
          </td>
          <td>
            {{ x.uploaded_at | date:"d/m/y" }}
          </td>
          <td>
            <a href="media/{{ x.certificado }}" target="_blank">
              <button class="btn btn-default btn-grad-green">
                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                DESCARGAR
              </button>
            </a>
          </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
  {% else %}
    <!--p>Ningún certificado coincide con el criterio de búsqueda.</p-->
  {% endif %}
</div>
<script type="text/javascript">
  function checkform(theform){
    var why = "";

    if(theform.txtInput1.value == ""){
      why += "El código de seguridad no debe estar vacío.\n";
    }
    if(theform.txtInput1.value != ""){
      if(ValidCaptcha(theform.txtInput1.value) == false){
        why += "El código de seguridad no coincide.\n";
      }
    }
    if(why != ""){
      alert(why);
      return false;
    }
  }

  //Generates the captcha function
  var a = Math.ceil(Math.random() * 9)+ '';
  var b = Math.ceil(Math.random() * 9)+ '';
  var c = Math.ceil(Math.random() * 9)+ '';
  var d = Math.ceil(Math.random() * 9)+ '';
  var e = Math.ceil(Math.random() * 9)+ '';

  var code = a + b + c + d + e;
  //alert (code);
  document.getElementById("txtCaptcha").value = code;
  document.getElementById("txtCaptchaDiv").innerHTML = code;

  // Validate the Entered input aganist the generated security code function
  function ValidCaptcha(){
      var str1 = document.getElementById('txtCaptcha').value;
      var str2 = document.getElementById('txtInput1').value;
      if (str1 == str2){
      return true;
    } else {
      return false;
    }
  }
</script>
{% endblock %}

registro/templates/registro/certificado_confirm_delete.html
{% extends "registro/base.html" %}
{% block titulo %}Repositorio de certificados digitales de CENDITEL{% endblock %}
{% block cuerpo %}
<form method="post">{% csrf_token %}
  Está seguro que desea eliminar el certificado de: "{{ object }}" ?
  <br />
  <br />
  <input type="submit" class="btn btn-danger" value="Borrar" />
</form>
{% endblock %}

registro/templates/registro/editar_certificado.html
{% extends "registro/base.html" %}
{% block titulo %}Editar certificado{% endblock %}
{% block cuerpo %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}

  <label>{{ form.certificado.label }}:</label>
  {{ form.certificado }}

  <hr />

  <label>Nombre completo:</label>
  {{ form.nombre_completo }}

  <hr />

  <label>Evento / Curso:</label>
  {{ form.evento_curso }}

  <hr />

  <label>Rol:</label>
  {{ form.rol }}

  <hr />

  <label>Cédula asociada:</label>
  {{ form.cedula }}

  <hr />

  <label>Fecha:</label> 
  {{ form.uploaded_at }} Ejemplo: 16/09/20 00:00:00

  <hr />

  <button type="submit">ACTUALIZAR</button>
</form>
{% endblock %}

registro/templates/registro/guardar_certificado.html
{% extends "registro/base.html" %}
{% block titulo %}Guardar certificado{% endblock %}
{% block cuerpo %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}

  <label>{{ form.certificado.label }}:</label>
  {{ form.certificado }}

  <hr />

  <label>Nombre completo:</label>
  {{ form.nombre_completo }}

  <hr />

  <label>Evento / Curso:</label>
  {{ form.evento_curso }}

  <hr />

  <label>Rol:</label>
  {{ form.rol }}

  <hr />

  <label>Cédula asociada:</label>
  {{ form.cedula }}

  <hr />

  <label>Fecha:</label>
  {{ form.uploaded_at }}
  <br />
  Ejemplo: 16/09/20 00:00:00

  <hr />

  <button type="submit">GUARDAR</button>
</form>
{% endblock %}

registro/templates/registro/index.html
{% extends "registro/base.html" %}
{% block titulo %}Repositorio de certificados digitales{% endblock %}
{% block cuerpo %}
<div align="center">
  <h1>Bienvenido al repositorio de certificados digitales de CENDITEL.</h1>
</div>
{% endblock %}

registro/templates/registro/lista_certificados.html
{% extends "registro/base.html" %}
{% block titulo %}Lista de certificados{% endblock %}
{% block cuerpo %}
<h1>Lista de certificados</h1>
<br />
<table class="table table-striped">
  <thead>
    <tr>
      <th><b>ID</b></th>
      <th><b>Nombre y Apellido</b></th>
      <th><b>Cédula o ID</b></th>
      <th><b>Evento / Curso</b></th>
      <th><b>Rol</b></th>
      <th><b>Fecha</b></th>
      <th><b>Ubicación electrónica</b></th>
      <th><b>Acciones</b></th>
    </tr>
  </thead>
  {% for x in object_list %}
  <tbody>
    <tr>
      <td>
        {{ x.id }}
      </td>
      <td>
        {{ x.nombre_completo }}
      </td>
      <td>
        {{ x.cedula }}
      </td>
      <td>
        {{ x.evento_curso }}
      </td>
      <td>
        {{ x.rol }}
      </td>
      <td>
        {{ x.uploaded_at | date:"d/m/Y" }}
      </td>
        <td>
          <a href="media/{{ x.certificado }}" target="_blank">
            <button class="btn btn-warning">
              <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
              DESCARGAR
            </button>
          </a>
        </td>
      <td>
        <a href="{% url 'registro:editar_certificado' x.id %}">
          <button class="btn btn-primary">EDITAR</button>
        </a>
      </td>
      <td>
        <a href="{% url 'registro:borrar_certificado' x.id %}">
          <button class="btn btn-danger">BORRAR</button>
        </a>  
      </td>
    </tr>
  </tbody>
  {% endfor %}
</table>
{% endblock %}

registro/templates/registro/subir_data.html
{% extends "registro/base.html" %}
{% block titulo %}Subir data zip{% endblock %}
{% block cuerpo %}
<h2>Subir data .zip</h2>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
  <label>{{ form.data_zip.label }}:</label>
  {{ form.data_zip }}
  <hr />
  <label>{{ form.descripcion.label }}:</label>
  {{ form.descripcion }}
  <button type="submit">Subir .zip</button>
</form>
{% endblock %}

registro/templates/registro/subir_data_csv.html
{% extends "registro/base.html" %}
{% block titulo %}Subir data csv{% endblock %}
{% block cuerpo %}
<h2>Subir data .csv</h2>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
  <label>{{ form.data_zip.label }}:</label>
  {{ form.data_zip }}
  <hr />
  <label>{{ form.descripcion.label }}:</label>
  {{ form.descripcion }}
  <button type="submit">Subir .csv</button>
</form>
{% endblock %}